### ISSUE TITLE
O3653-16 Excel

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#105]
Module Number: O3653-16 Excel
Module Title: Microsoft Graph and the Excel REST API
Path of file:
### Details of issue

Lab cannot build due to RESTAPIHelper does not exist error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'RESTAPIHelper' does not exist in the current context	ExcelRestAPI-ToDoList	C:\Dev\ExcelRestAPI-ToDoList\ExcelRestAPI-ToDoList\Controllers\ToDoListController.cs	26	Active

**Comment by sumurthy** [comment]
The RESTAPIHelper needs to be added to the project as described. Are you getting this error past that step?

**Comment by lucas66** [comment]
I see.  The file is ExcelAPIHelper and RESTAPIHelper is the class.  Would you like to make the names match?

**Comment by jamescro** [comment]
I've resolved the mismatch between the file name and the class name in the sample that we'll be publishing. I wouldn't want to change it in the quick start at this late stage, though, since we'd have to update the screen shots, retest, etc. I've run through the quick start on the VM and have confirmed that the code works as-is.
