### ISSUE TITLE
Starter files in Connector lab need to change

### ISSUE THREAD

**Issue by jthake** [OfficeDev/office-docs#88]
Module Number: O3653-21 Connectors
Module Title: Learn how to build Office 365 Connectors using Webhooks
Path of file:https://github.com/OfficeDev/office-docs/blob/master/O3653/O3653-21%20Connectors/Quick%20Start%20Lab%20-%20Office%20365%20Connectors%20Lab.md
### Details of issue

I raised a concern with Pretish on the Connectors lab…it essentially refers to github. The student has no context of github. E.g. if you launch this lab https://labondemand.com/Console/de799c8f-0e9c-4251-96dc-27b973955770?rc=200 the lab instructions are on the right hand side and in an iframe with no reference to github. The contents of the github repo has been pulled as of yesterday, so if you want o reference any files, you need to reference the location on the harddrive of the url. 

E.g. I have suggested to Pretish that he change his instructions from:

“6. Find the "Completed Projects" folder under lab "O3653-21". You will find this folder in the same Github repo location that host the instructions for this exercise. You will need to copy a few files from this already completed projects folder in order to complete this exercise.
7. Find all the Swift*.cs files under the Models folder in "Completed Projects". Copy these files to the Models folder in your Visual Studio project. Right-click the Models folder, select Add>Existing item and add these files into your Visual Studio project. Do the same for GithubIssueEvent.cs, ConnectorCard.cs and add them to your Visual Studio project.”

To

“6. Navigate to “C:\git\trainingcontent-nda\O3653\O3653-21 Connectors\Completed Projects\Github Webhooks\WebApplication1\Models\” in Windows Explorer. 
7. Copy all the files in this directory that begin with “Swift” to the Models folder in your Visual Studio project. Right-click the Models folder, select Add>Existing item and add these files into your Visual Studio project. Do the same for GithubIssueEvent.cs, ConnectorCard.cs and add them to your Visual Studio project.”

**Comment by pretish** [comment]
Hi Jeremy
I fixed this and some other minor updates. Thanks for catching it
Can you please pull my changes?

Get Outlook<https://aka.ms/uzin6x>




On Fri, Mar 25, 2016 at 10:51 AM -0700, "Jeremy Thake" <notifications@github.com<mailto:notifications@github.com>> wrote:


Module Number: O3653-21 Connectors
Module Title: Learn how to build Office 365 Connectors using Webhooks
Path of file:https://github.com/OfficeDev/office-docs/blob/master/O3653/O3653-21%20Connectors/Quick%20Start%20Lab%20-%20Office%20365%20Connectors%20Lab.md

Details of issue

I raised a concern with Pretish on the Connectors lab...it essentially refers to github. The student has no context of github. E.g. if you launch this lab https://labondemand.com/Console/de799c8f-0e9c-4251-96dc-27b973955770?rc=200<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2flabondemand.com%2fConsole%2fde799c8f-0e9c-4251-96dc-27b973955770%3frc%3d200&data=01%7c01%7cpretisha%40exchange.microsoft.com%7c1b03c6d8c28a4119ad4a08d354d620a7%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=eMxX55AsYqS5visFjO6sCA7ZaM4%2fH92OgVwlbdP7G1s%3d> the lab instructions are on the right hand side and in an iframe with no reference to github. The contents of the github repo has been pulled as of yesterday, so if you want o reference any files, you need to reference the location on the harddrive of the url.

E.g. I have suggested to Pretish that he change his instructions from:

"6. Find the "Completed Projects" folder under lab "O3653-21". You will find this folder in the same Github repo location that host the instructions for this exercise. You will need to copy a few files from this already completed projects folder in order to complete this exercise.
7. Find all the Swift*.cs files under the Models folder in "Completed Projects". Copy these files to the Models folder in your Visual Studio project. Right-click the Models folder, select Add>Existing item and add these files into your Visual Studio project. Do the same for GithubIssueEvent.cs, ConnectorCard.cs and add them to your Visual Studio project."

To

"6. Navigate to "C:\git\trainingcontent-nda\O3653\O3653-21 Connectors\Completed Projects\Github Webhooks\WebApplication1\Models\" in Windows Explorer.
7. Copy all the files in this directory that begin with "Swift" to the Models folder in your Visual Studio project. Right-click the Models folder, select Add>Existing item and add these files into your Visual Studio project. Do the same for GithubIssueEvent.cs, ConnectorCard.cs and add them to your Visual Studio project."

-

**Comment by pretish** [comment]
Fixed the md file to pull the starter files from the local directory for the VM machine
