### ISSUE TITLE
O3654-1 MailHelper.cs file throws error

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#97]
Module Number: O3654-1
Module Title: Connect to the Microsoft Graph from a Windows Universal App
Path of file:
### Details of issue

Line 45 of the MailHelper.cs file needs to have lowercase 'html':
![image](https://cloud.githubusercontent.com/assets/17051339/14086158/835b8c76-f4d8-11e5-989a-e934ab857ef2.png)

![image](https://cloud.githubusercontent.com/assets/17051339/14086202/c1c348fa-f4d8-11e5-911b-1dd5f04d6a03.png)

**Comment by jamescro** [comment]
Not with the latest version of the SDK -- 1.0.5-rc

**Comment by lucas66** [comment]
I noticed 1.0.5-rc was not available to install from NuGet.

**Comment by jamescro** [comment]
It will be available on NuGet by Tuesday. Hit me up directly for the current location of the package.

**Comment by jamescro** [comment]
You can find the updated SDK here: \\ginach-main\share\GraphSdk

**Comment by jthake** [comment]
@lucas66 does not have access to this. There is a copy on the student vm though, @jamescro can you make sure that this is compatible? c:\graphSDK\

**Comment by jamescro** [comment]
That's an earlier version of the library (1.0.3-rc as opposed to 1.0.5-rc). This will be moot after tomorrow (or it should be), since that NuGet package should be published on nuget.org by then. When you upgrade to 1.0.5-rc you'll notice that the casing switches to standard C# across the board (so BodyType.Html instead of BodyType.html) and the GraphClient.Dispose() method goes away. The code in the quick start has been updated to reflect those changes.
